In [5]:
# การระบุชนิดข้อมูล หากสร้างอาร์เรย์โดยไม่ระบุชนิดข้อมูล numpy จะพยายามแปลงค่าให้สมาชิกุกตัวเป็นข้อมูลชนิดใดชนิดหนึ่งที่สามารถเป็นไปได้เหมือนๆกัน
import numpy as np

a = np.array([1,5,6,7])
b = np.array([1,True,'Three',5.0])
# sep การกำหนด การขึ้นบรรทัดใหม่
print(a,b,sep = '\n\n') 


[1 5 6 7]

['1' 'True' 'Three' '5.0']


In [21]:
# data type (dtype) การแปลงชนิดข้อมูล
# กรณีแปลงค่าใน python ปกติ
a = 5
print(a)
print('เปลี่ยนเป็นทศนิยม : ',float(a))

# แปลงค่าใน numpy
import numpy as np
b = np.array([1,2,3,4,5],dtype = float)
c = np.array([1.23, 5.666,7.888],dtype = int)
d = np.array([True,False], dtype = str)

print(b,c,d,sep='\n\n')

5
เปลี่ยนเป็นทศนิยม :  5.0
[1. 2. 3. 4. 5.]

[1 5 7]

['True' 'False']
