In [2]:
# การสร้างอาร์เรย์แบบใช้ข้อมูลค่าเดียวกัน
import numpy as np
# zeros() สร้างอาร์เรย์โดยให้สมาชิกมีค่าเริ่มแรกเป็น 0 ทั้งหมด
# zeros(size,dtype) ค่าปกติจะเป็น 0. 
z = np.zeros(5)
zi = np.zeros(5,dtype=int)

# ones() สร้างอาร์เรย์โดยให้สมาชิกทุกตัวมีค่าเริ่มแรกเป็น 1 ทั้งหมด
o = np.ones(5)
oi = np.ones(5,dtype=int)

# full() สร้างอาร์เรย์โดยกำหนดจำนวนสมาชิกและค่าเริ่มต้นตามที่ระบุ

# full(size,dtype)

f1 = np.full(5,10)
f2 = np.full(5,15)
f3 = np.full(5,5.55, dtype=int)

print(z,zi,o,oi,f1,f2,f3, sep='\n\n')

[0. 0. 0. 0. 0.]

[0 0 0 0 0]

[1. 1. 1. 1. 1.]

[1 1 1 1 1]

[10 10 10 10 10]

[15 15 15 15 15]

[5 5 5 5 5]
