In [2]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[0],a[1],a[2],sep='\n\n')

[1 2 3]

[4 5 6]

[7 8 9]


In [9]:
# array()  อาจกำหนดสมาชิกลงไปโดยตรงหรือจะสร้างเป็นลิสต์ 2 มิติลงไปก็ได้
import numpy as np

# กำหนดสมาชิกลงไปโดยตรง
a1 = np.array([[10,20,30,40],[50,60,70,80],[11,22,33,44],[55,66,77,88]])
# สร้างเป็นลิสต์
list2d = [[10,20,30,40],[50,60,70,80]]

print(a1)
print(list2d)

# นำลิสต์ที่สร้างใส่ไปใน array
a2 = np.array(list2d)
a2


[[10 20 30 40]
 [50 60 70 80]
 [11 22 33 44]
 [55 66 77 88]]
[[10, 20, 30, 40], [50, 60, 70, 80]]


array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [5]:
# zeros([rows,cols])  ระบุจำนวนแถวและคอลัมน์ สมาชิกทุกตัวมีค่าริ่มต้นเป็น 0
# ones([rows,cols]) ระบุจำนวนแถวและคอลัมน์ สมาชิกทุกตัวมีค่าริ่มต้นเป็น 1
# full([rows,cols],value)  ระบุจำนวนแถวและคอลัมน์ พร้อมกับค่าเริ่มต้นที่ต้องการ

import numpy as np
a0 = np.zeros([3,4] ,dtype=int)
a1 = np.ones([4,6],dtype = int)
af = np.full([4,4],10)

print(a0,a1,af, sep='\n\n')


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [11]:
# random.randint(low, high, [rows,cols])  สร้างอาร์เรย์ของเลขจำนวนเต็มภายในช่วงที่ระบุ
#  random.uniform(low, high, [rows,cols])  สร้างอาร์เรย์ของเลขทศนิยมภายในช่วงที่ระบุ
# random.rand(rows , cols)  สร้างอาร์เรย์ที่เป็นเลขทศนิยมระหว่าง 0.0 - 1.0 
# random.choice([sequence] , [rows,cols])  สุ่มค่าจากรายการตัวเลือกที่กำหนด พร้อมระบุจำนวนแถวและคอลัมน์

import numpy as np

# สร้างอาร์เรย์แบบสุ่มตัวเลขจำนวนเต็มตั้งแต่ 10 - 101 มา 5 แถว 5 คอลัมน์
rand_int  = np.random.randint(10,101,[5,5])

# สร้างอาร์เรย์แบบสุ่มตัวเลขทศนิยมตั้งแต่ 1 - 11 มา 4 แถว 5 คอลัมน์
uniform = np.random.uniform(1,11,(4,5))

#  สร้างอาร์เรย์ที่เป็นเลขทศนิยมระหว่าง 0.0 - 1.0 มา 6 แถว 5 คอลัมน์
rand = np.random.rand(6,5)

# สุ่มค่าจากรายการตัวเลือก ดังนี้ 3.114,0.345,-10,9.99,33,-2.57  มา 3 แถว 4 คอลัมน์
choice = np.random.choice([3.114,0.345,-10,9.99,33,-2.57],(3,4))

print(rand_int,uniform,rand,choice, sep='\n\n')

[[16 48 65 71 90]
 [30 53 67 14 41]
 [85 21 34 62 47]
 [95 28 67 84 80]
 [13 82 85 25 64]]

[[ 9.81444276  4.46090016 10.72667351  2.96672892  7.88546671]
 [ 9.02376056  3.02097573  6.65253064  9.66442908  9.93788796]
 [ 1.12049539  7.66272736  7.98874104  3.06228926  8.19481571]
 [ 9.66383502  8.11924272  5.10908112  5.37720336  9.50836162]]

[[0.82750284 0.78464099 0.07263712 0.33149537 0.77133314]
 [0.52310664 0.83200665 0.03606329 0.97344573 0.94242398]
 [0.87243777 0.25235581 0.44271423 0.15564917 0.62984355]
 [0.08886063 0.73172642 0.28665377 0.8167594  0.45144328]
 [0.61722429 0.49060508 0.12506801 0.93043019 0.33448401]
 [0.3148786  0.14076878 0.15303425 0.82034449 0.26920806]]

[[  9.99    9.99    0.345   3.114]
 [ -2.57   33.      0.345  33.   ]
 [ 33.    -10.      9.99    3.114]]


In [30]:
# การเข้าถึงสมาชิกของอาร์เรย์ 2 มิติ
# array[ลำดับแถว , ลำดับคอลัมน์]
import numpy as np

a = np.random.randint(1,11,[3,4])

print(a,'\n')
print('แถวที่ 1 :',a[1])
print('แถวที่ 2 :',a[2],'\n')
print('แถวที่ 1 คอลัมที่ 2 คือ :',a[1][2])
print('แถวที่ 0 คอลัมที่ 3 คือ :',a[0][3])

[[10  9  3  4]
 [10  1  4  3]
 [ 7  8  7  9]] 

แถวที่ 1 : [10  1  4  3]
แถวที่ 2 : [7 8 7 9] 

แถวที่ 1 คอลัมที่ 2 คือ : 4
แถวที่ 0 คอลัมที่ 3 คือ : 4


In [49]:
# หากต้องการเข้าถึงสมาชิกที่เป็นลำดับต่อเนื่องกัน สามารถใช้วิธี index slicing ได้
# รูปแบบ array[start : stop : step , start : stop : step ]   กลุ่มแรกคือลำดับแถว กลุ่มหลังคือลำดับคอลัมน์

import numpy as np
a = np.random.randint(1,11,[6,6])
print(a,'\n')
print('ข้อมูลช่วง แถวที่ 1 - 4 และ คอลัมน์ที่ 2 - 3 : \n',a[1:5, 2:4],'\n')
print('ข้อมูลช่วง แถวที่ 0 - 3 และคอลัมน์ที่ 2 - 3 :\n',a[:4,2:],'\n')
print('เลือกทุกแถว และ คอลัมน์ที่ 0-5 โดยมีระยะห่างระหว่างข้อลัมน์ เท่ากับ 2 :\n',a[:: , :6:2])


[[ 6  9  2  3  8  8]
 [10  7  8  8  3  1]
 [10  3  6  4  1  1]
 [ 2 10  1  3 10  6]
 [ 5  6 10  2  7  3]
 [ 5  5 10  5  5  9]] 

ข้อมูลช่วง แถวที่ 1 - 4 และ คอลัมน์ที่ 2 - 3 : 
 [[ 8  8]
 [ 6  4]
 [ 1  3]
 [10  2]] 

ข้อมูลช่วง แถวที่ 0 - 3 และคอลัมน์ที่ 2 - 3 :
 [[ 2  3  8  8]
 [ 8  8  3  1]
 [ 6  4  1  1]
 [ 1  3 10  6]] 

เลือกทุกแถว และ คอลัมน์ที่ 0-5 โดยมีระยะห่างระหว่างข้อลัมน์ เท่ากับ 2 :
 [[ 6  2  8]
 [10  8  3]
 [10  6  1]
 [ 2  1 10]
 [ 5 10  7]
 [ 5 10  5]]
